sentencas_alteradas = {
    "P9.1": "PEITO DOR O U FALTAR A R INSPIRAR PIORAR MOMENTO CORPO ESFORÇAR",
    "P9.2": "SUBIR-ESCADA CORPO PIOR",
    "P9.3": "PLANO ANDAR CORPO PIOR",
    "P9.4": "TOMAR-BANHO CORPO PIOR",
    "P9.6": "SUBIR-ESCADA CORPO PIOR",
    "158": "SUBIR-ESCADA CORPO PIOR",
    "159": "SUBIR-ESCADA CORPO PIOR NÃO",
    "161": "PLANO ANDAR CORPO PIOR NÃO"
}