feeder: dataset.dataloader_in_chroma_int_npz_kornia_hfps.BaseFeeder
phase: train
dataset: captar-libras_10-12

num_epoch: 101
work_dir: ./work_dir/captar-libras_10-12_c_in_int-npz_kornia_hf/
batch_size: 2
# grad_accumulation_steps: Number of batches for which gradients are accumulated before performing a weights update.
grad_accumulation_steps: 2
random_seed: 0
test_batch_size: 1
num_worker: 32
device: 0
log_interval: 50
eval_interval: 1
save_interval: 5
# python in default
#evaluate_tool: sclite
evaluate_tool: python
loss_weights:
  SeqCTC: 1.0
  # VAC
  # ConvCTC: 1.0
  # Dist: 10.0
load_weights: ''

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [ 40, 65, 80, 90, 95]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0
  kornia_kwargs:
    brightness:
      brightness: [0.3, 1.7]
      clip_output: True
      same_on_batch: True
      p: 0.5
      keepdim: True
    contrast:
      contrast: [0.5, 1.5]
      clip_output: True
      same_on_batch: True
      p: 0.5
      keepdim: True
    gaussian_noise:
      mean: 0
      std: 0.6
      same_on_batch: True
      p: 1
      keepdim: True
    sharpness:
      sharpness: [0.4, 1.6]
      p: 0.5
      same_on_batch: True
      keepdim: True
    affine:
      degrees: 5
      translate: [0.05, 0.05]
      p: 0.5
      same_on_batch: True
      keepdim: True
    perspective:
      distortion_scale: 0.2
      p: 0.1
      keepdim: True
      same_on_batch : True
    #motion_blur:
      #kernel_size: 7
      #angle: [0, 360]
      #direction: [0.2, 0.8]
      #border_type: 0
      #resample: 
      #p: 0.5
      #keepdim: True
    #planckian_jitter:
      #mode: blackbody
      #same_on_batch: True
      #p: 0.05
      #keepdim: True
    #plasma_brightness:
      #roughness: [0.1, 0.7]
      #intensity: [0.0, 0.6]
      #same_on_batch: True
      #p: 0.1
      #keepdim: True

model: slr_network.SLRModel
decode_mode: beam
model_args:
  num_classes: 1296
  c2d_type: resnet18
  conv_type: 2
  use_bn: 1
  # SMKD
  share_classifier: True
  weight_norm: True

wandb_args:
  active: True
  wandb_key: './configs/wandb.key'

